name: Generate UML Diagram and Code Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Python and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install javalang

    - name: Generate UML Diagram and Code Data
      run: |
        python3 generate_plantuml.py

    - name: Render UML Diagram
      run: |
        sudo apt-get install -y plantuml
        plantuml uml_diagram.puml

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md uml_diagram.png code_data.txt
        git commit -m 'Update UML Diagram and Code Data in README'
        git push
        
      continue-on-error: true
